apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    app: explorer
  namespace: besu
spec:
  type: NodePort
  selector:
    app: explorer
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010
      protocol: TCP
      name: explorer