---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer
  labels:
    app: explorer
  namespace: besu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: explorer
  template:
    metadata:
      labels:
        app: explorer
    spec:
      containers:
        - name: explorer
          image: quorum-dev-quickstart/block-explorer-light:develop
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          volumeMounts:
            - name: nginx-configmap-default
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
              readOnly: true
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
      volumes:
        - name: nginx-configmap-default
          configMap:
            name: explorer-nginx-configmap-default